[project]
name = "githacker"
version = "1.1.3"
description = "A multiple threads tool to download the `.git` folder and rebuild git repository locally."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "coloredlogs>=15.0.1",
    "gitpython>=3.1.45",
    "requests>=2.32.5",
    "rich>=14.2.0",
]
