"""Unit tests for benchmark.compare — exercises the file-by-file diff
without spinning up docker or generating a real repo."""

from __future__ import annotations

from benchmark.compare import _compare_file_list, _md5, compare_repos


def test_md5_matches_known_vector():
    # Anchored against an externally computed checksum so a future
    # refactor to the digest function would break this test.
    assert _md5(b"hello") == "5d41402abc4b2a76b9719d911017c592"


def test_compare_file_list_counts_match_diff_absent(tmp_path):
    origin = tmp_path / "origin"
    recovered = tmp_path / "recovered"
    origin.mkdir()
    recovered.mkdir()

    (origin / "a.txt").write_bytes(b"same")
    (recovered / "a.txt").write_bytes(b"same")

    (origin / "b.txt").write_bytes(b"original")
    (recovered / "b.txt").write_bytes(b"different")

    (origin / "c.txt").write_bytes(b"only in origin")
    # c.txt absent in recovered

    (origin / "ignored").mkdir()  # not a file — skipped by `is_file()`

    correct, total, different, absent = _compare_file_list(
        origin, recovered, ["a.txt", "b.txt", "c.txt", "ignored"],
    )
    assert (correct, total) == (1, 3)
    assert different == ["b.txt"]
    assert absent == ["c.txt"]


def test_compare_file_list_treats_index_as_correct(tmp_path):
    """`.git/index` is regenerated by `git clone`, so an exact byte match is
    not expected; the comparator counts it as correct regardless."""
    origin = tmp_path / "origin"
    recovered = tmp_path / "recovered"
    (origin / ".git").mkdir(parents=True)
    (recovered / ".git").mkdir(parents=True)
    (origin / ".git" / "index").write_bytes(b"AAA")
    (recovered / ".git" / "index").write_bytes(b"BBB")

    correct, total, _diff, _abs = _compare_file_list(
        origin, recovered, [".git/index"],
    )
    assert (correct, total) == (1, 1)


def test_compare_repos_aggregates_per_feature(tmp_path):
    origin = tmp_path / "origin"
    recovered = tmp_path / "recovered"
    origin.mkdir()
    recovered.mkdir()

    (origin / "src.py").write_bytes(b"code")
    (recovered / "src.py").write_bytes(b"code")
    (origin / "branch.txt").write_bytes(b"x")
    # branch.txt absent in recovered

    manifest = {
        "source_code": ["src.py"],
        "branches": ["branch.txt"],
        "tags": [],  # vacuously supported when no files exist
    }
    result = compare_repos(origin, recovered, manifest)

    assert result.features["source_code"].ratio == 100.0
    assert result.features["source_code"].supported is True

    assert result.features["branches"].ratio == 0.0
    assert result.features["branches"].supported is False
    assert "branch.txt" in result.absent_files

    # No files to compare — supported is True (vacuous), ratio is 0.
    assert result.features["tags"].supported is True
    assert result.features["tags"].total == 0

    # Overall: 1 of 2 actual files matched.
    assert result.correct == 1
    assert result.total == 2
    assert result.ratio == 50.0
